### ISSUE TITLE
Design combat mechanics v1

### ISSUE THREAD

**Issue by gvenour** [Josef-Gray/adorable-hopelessness#2]
We need a system for resolving combat outcomes.

## Acceptance criteria

- A comment (or multiple comments) exist on this issue, describing one or more possible approaches to resolve combat outcomes.

**Comment by Josef-Gray** [comment]
I suggest a combat mechanic of always hitting - so we don't need to work out complex hit or miss mechanics.  Abilities, spells and character statistics will be more focussed in modifying damage output and or other effects.

**Comment by Josef-Gray** [comment]
Example of initial combat scenario:
Avatar will swing for 1-3 damage per hit. Avatar will start with 10hp.
Enemy rat will swing for 1-2 damage per hit. Rat will start with 10hp.
Combat will end when either one reaches 0hp.
